apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-abgi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-abgi
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-abgi
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-abgi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-abgi
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dkyo-tenant/rhtap-demo-app/hacbs-test-project-abgi@sha256:94fd685cdd9b97ad4ca6a908586a70e7f28c64189c20c1aea0ee357ee45bae31
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
